In [1]:
import numpy as np
import pandas as pd

In [40]:
df_train=pd.read_csv("C:\\Sridhar\\AI_ML\\Algorithms\\datasets\\HomePrices\\train.csv")
df_holdout=pd.read_csv("C:\\Sridhar\\AI_ML\\Algorithms\\datasets\\HomePrices\\test.csv")

In [41]:
df_train.shape, df_holdout.shape

((1460, 81), (1459, 80))

In [42]:
df_train = df_train[df_train.describe().columns]

In [43]:
df_train.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.00,8450,7,5,2003,2003,196.00,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.00,9600,6,8,1976,1976,0.00,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.00,11250,7,5,2001,2002,162.00,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.00,9550,7,5,1915,1970,0.00,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.00,14260,8,5,2000,2000,350.00,655,...,192,84,0,0,0,0,0,12,2008,250000

In [44]:
df_train.drop('Id',axis=1,inplace=True)

In [45]:
pd.isnull(df_train).sum()

MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SalePrice          0
dtype: int64

In [46]:
y=df_train['SalePrice']
x=df_train.drop('SalePrice',axis=1)

In [47]:
y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [48]:
x.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,60,65.00,8450,7,5,2003,2003,196.00,706,0,...,548,0,61,0,0,0,0,0,2,2008
1,20,80.00,9600,6,8,1976,1976,0.00,978,0,...,460,298,0,0,0,0,0,0,5,2007
2,60,68.00,11250,7,5,2001,2002,162.00,486,0,...,608,0,42,0,0,0,0,0,9,2008
3,70,60.00,9550,7,5,1915,1970,0.00,216,0,...,642,0,35,272,0,0,0,0,2,2006
4,60,84.00,14260,8,5,2000,2000,350.00,655,0,...,836,192,84,0,0,0,0,0,12,2008

In [49]:
# df_train.fillna(20,inplace=True)
for i in df_train.columns:
    df_train[i].fillna(df_train[i].median(),inplace=True)

for i in df_train.columns:
    df_train[i].fillna(df_train[i].mode().values[0],inplace=True)

In [50]:
df_train

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,60,65.00,8450,7,5,2003,2003,196.00,706,0,...,0,61,0,0,0,0,0,2,2008,208500
1,20,80.00,9600,6,8,1976,1976,0.00,978,0,...,298,0,0,0,0,0,0,5,2007,181500
2,60,68.00,11250,7,5,2001,2002,162.00,486,0,...,0,42,0,0,0,0,0,9,2008,223500
3,70,60.00,9550,7,5,1915,1970,0.00,216,0,...,0,35,272,0,0,0,0,2,2006,140000
4,60,84.00,14260,8,5,2000,2000,350.00,655,0,...,192,84,0,0,0,0,0,12,2008,250000
5,50,85.00,14115,5,5,1993,1995,0.00,732,0,...,40,30,0,320,0,0,700,10,2009,143000
6,20,75.00,10084,8,5,2004,2005,186.00,1369,0,...,255,57,0,0,0,0,0,8,2007,307000
7,60,69.00,10382,7,6,1973,1973,240.00,859,32,...,235,204,228,0,0,0,350,11,2009,200000
8,50,51.00,6120,7,5,1931,1950,0.00,0,0,...,90,0,205,0,0,0,0,4,2008,129900
9,190,50.00,7420,5,6,1939,1950,0.00,851,0,...,0,4,0,0,0,0,0,1,2008,118000
10,20,70.00,11200,5,5,1965,1965,0.00,906,0,...,0,0,0,0,0,0,0,2,2008,129500
11,60,85.00,11924,9,5,2005,2006,286.00,998,0,...,147,21,0,0,0,0,0,7,2006,345000
12,20,69.00,12968,5,6,1962,1962,0.00,737,0,...,140,0,0,0,176,0,0,9,2008,144000
13,20,91.00,10652,7,5,2006,2007,306.00,0,0,...,160,33,0,0,0,0,0,8,2007,279500
14,20,69.00,10920,6,5,1960,1960,212.00,733,0,...,0,213,176,0,0,0,0,5,2008,157000
15,45,51.00,6120,7,8,1929,2001,0.00,0,0,...,48,112,0,0,0,0,0,7,2007,132000
16,20,69.00,11241,6,7,1970,1970,180.00,578,0,...,0,0,0,0,0,0,700,3,2010,149000
17,90,72.00,10791,4,5,1967,1967,0.00,0,0,...,0,0,0,0,0,0,500,10,2006,90000
18,20,66.00,13695,5,5,2004,2004,0.00,646,0,...,0,102,0,0,0,0,0,6,2008,159000
19,20,70.00,7560,5,6,1958,1965,0.00,504,0,...,0,0,0,0,0,0,0,5,2009,139000
20,60,101.00,14215,8,5,2005,2006,380.00,0,0,...,240,154,0,0,0,0,0,11,2006,325300
21,45,57.00,7449,7,7,1930,1950,0.00,0,0,...,0,0,205,0,0,0,0,6,2007,139400
22,20,75.00,9742,8,5,2002,2002,281.00,0,0,...,171,159,0,0,0,0,0,9,2008,230000
23,120,44.00,4224,5,7,1976,1976,0.00,840,0,...,100,110,0,0,0,0,0,6,2007,129900
24,20,69.00,8246,5,8,1968,2001,0.00,188,668,...,406,90,0,0,0,0,0,5,2010,154000
25,20,110.00,14230,8,5,2007,2007,640.00,0,0,...,0,56,0,0,0,0,0,7,2009,256300
26,20,60.00,7200,5,7,1951,2000,0.00,234,486,...,222,32,0,0,0,0,0,5,2010,134800
27,20,98.00,11478,8,5,2007,2008,200.00,1218,0,...,0,50,0,0,0,0,0,5,2010,306000
28,20,47.00,16321,5,6,1957,1997,0.00,1277,0,...,288,258,0,0,0,0,0,12,2006,207500
29,30,60.00,6324,4,6,1927,1950,0.00,0,0,...,49,0,87,0,0,0,0,5,2008,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,60,60.00,21930,5,5,2005,2005,0.00,0,0,...,100,40,0,0,0,0,0,7,2006,192140
1431,120,69.00,4928,6,6,1976,1976,0.00,958,0,...,0,60,0,0,0,0,0,10,2009,143750
1432,30,60.00,10800,4,6,1927,2007,0.00,0,0,...,0,0,0,0,0,0,0,8,2007,64500
1433,60,93.00,10261,6,5,2000,2000,318.00,0,0,...,0,0,0,0,0,0,0,5,2008,186500
1434,20,80.00,17400,5,5,1977,1977,0.00,936,0,...,295,41,0,0,0,0,0,5,2006,160000
1435,20,80.00,8400,6,9,1962,2005,237.00,0,0,...,0,36,0,0,0,0,0,7,2008,174000
1436,20,60.00,9000,4,6,1971,1971,0.00,616,0,...,0,0,0,0,0,0,0,5,2007,120500
1437,20,96.00,12444,8,5,2008,2008,426.00,1336,0,...,0,66,0,304,0,0,0,11,2008,394617
1438,20,90.00,7407,6,7,1957,1996,0.00,600,0,...,0,158,158,0,0,0,0,4,2010,149700
1439,60,80.00,11584,7,6,1979,1979,96.00,315,110,...,0,88,216,0,0,0,0,11,2007,197000
1440,70,79.00,11526,6,7,1922,1994,0.00,0,0,...,431,0,0,0,0,0,0,9,2008,191000
1441,120,69.00,4426,6,5,2004,2004,147.00,697,0,...,149,0,0,0,0,0,0,5,2008,149300
1442,60,85.00,11003,10,5,2008,2008,160.00,765,0,...,168,52,0,0,0,0,0,4,2009,310000
1443,30,69.00,8854,6,6,1916,1950,0.00,0,0,...,0,98,0,0,40,0,0,5,2009,121000
1444,20,63.00,8500,7,5,2004,2004,106.00,0,0,...,192,60,0,0,0,0,0,11,2007,179600
1445,85,70.00,8400,6,5,1966,1966,0.00,187,627,...,0,0,252,0,0,0,0,5,2007,129000
1446,20,69.00,26142,5,7,1962,1962,189.00,593,0,...,261,39,0,0,0,0,0,4,2010,157900
1447,60,80.00,10000,8,5,1995,1996,438.00,1079,0,...,0,65,0,0,0,0,0,12,2007,240000
1448,50,70.00,11767,4,7,1910,2000,0.00,0,0,...,168,24,0,0,0,0,0,5,2007,112000
1449,180,21.00,1533,5,7,1970,1970,0.00,553,0,...,0,0,0,0,0,0,0,8,2006,92000
1450,90,60.00,9000,5,5,1974,1974,0.00,0,0,...,32,45,0,0,0,0,0,9,2009,136000
1451,20,78.00,9262,8,5,2008,2009,194.00,0,0,...,0,36,0,0,0,0,0,5,2009,287090
1452,180,35.00,3675,5,5,2005,2005,80.00,547,0,...,0,28,0,0,0,0,0,5,2006,145000
1453,20,90.00,17217,5,5,2006,2006,0.00,0,0,...,36,56,0,0,0,0,0,7,2006,84500
1454,20,62.00,7500,7,5,2004,2005,0.00,410,0,...,0,113,0,0,0,0,0,10,2009,185000
1455,60,62.00,7917,6,5,1999,2000,0.00,0,0,...,0,40,0,0,0,0,0,8,2007,175000
1456,20,85.00,13175,6,6,1978,1988,119.00,790,163,...,349,0,0,0,0,0,0,2,2010,210000
1457,70,66.00,9042,7,9,1941,2006,0.00,275,0,...,0,60,0,0,0,0,2500,5,2010,266500
1458,20,68.00,9717,5,6,1950,1996,0.00,49,1029,...,366,0,112,0,0,0,0,4,2010,142125
1459,20,75.00,9937,5,6,1965,1965,0.00,830,290,...,736,68,0,0,0,0,0,6,2008,147500

In [51]:
from numpy.linalg import inv

In [52]:
p=np.dot(x,x.T)

In [53]:
p

array([[9.34608430e+07, 1.02334110e+08, 1.17273134e+08, ...,
        9.96990330e+07, 1.01815193e+08, 1.04873423e+08],
       [1.02334110e+08, 1.14024234e+08, 1.29355038e+08, ...,
        1.09018950e+08, 1.13322443e+08, 1.17032202e+08],
       [1.17273134e+08, 1.29355038e+08, 1.49073782e+08, ...,
        1.25551052e+08, 1.29236751e+08, 1.32814969e+08],
       ...,
       [9.96990330e+07, 1.09018950e+08, 1.25551052e+08, ...,
        1.14069390e+08, 1.08600139e+08, 1.11762127e+08],
       [1.01815193e+08, 1.13322443e+08, 1.29236751e+08, ...,
        1.08600139e+08, 1.14805933e+08, 1.16921774e+08],
       [1.04873423e+08, 1.17032202e+08, 1.32814969e+08, ...,
        1.11762127e+08, 1.16921774e+08, 1.20512480e+08]])

In [54]:
q = inv(p)

In [55]:
q

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [56]:
beta_coeff=np.dot((np.dot(x.T,inv(np.dot(x,x.T)))),y)

In [57]:
beta_coeff

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [58]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [59]:
pd.DataFrame([beta_coeff,x.columns]).T

      0              1
0   NaN     MSSubClass
1   NaN    LotFrontage
2   NaN        LotArea
3   NaN    OverallQual
4   NaN    OverallCond
5   NaN      YearBuilt
6   NaN   YearRemodAdd
7   NaN     MasVnrArea
8   NaN     BsmtFinSF1
9   NaN     BsmtFinSF2
10  NaN      BsmtUnfSF
11  NaN    TotalBsmtSF
12  NaN       1stFlrSF
13  NaN       2ndFlrSF
14  NaN   LowQualFinSF
15  NaN      GrLivArea
16  NaN   BsmtFullBath
17  NaN   BsmtHalfBath
18  NaN       FullBath
19  NaN       HalfBath
20  NaN   BedroomAbvGr
21  NaN   KitchenAbvGr
22  NaN   TotRmsAbvGrd
23  NaN     Fireplaces
24  NaN    GarageYrBlt
25  NaN     GarageCars
26  NaN     GarageArea
27  NaN     WoodDeckSF
28  NaN    OpenPorchSF
29  NaN  EnclosedPorch
30  NaN      3SsnPorch
31  NaN    ScreenPorch
32  NaN       PoolArea
33  NaN        MiscVal
34  NaN         MoSold
35  NaN         YrSold

### base model - with all variables variables

In [2]:
df_train=pd.read_csv("C:\\Sridhar\\AI_ML\\Algorithms\\datasets\\HomePrices\\train.csv")
df_holdout=pd.read_csv("C:\\Sridhar\\AI_ML\\Algorithms\\datasets\\HomePrices\\test.csv")

In [3]:
df_train.shape,df_holdout.shape

((1460, 81), (1459, 80))

In [4]:
from sklearn.preprocessing import LabelEncoder
for i in df_train.describe(include='object').columns:
    le=LabelEncoder()
    le.fit(df_train[i].astype(str))
    t=le.transform(df_train[i].astype(str))
    df_train[i]=t

In [5]:
df_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,2,3,3,0,...,0,3,4,4,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,2,3,3,0,...,0,3,4,4,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,2,0,3,0,...,0,3,4,4,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,2,0,3,0,...,0,3,4,4,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,2,0,3,0,...,0,3,4,4,0,12,2008,8,4,250000

In [6]:
df_train.drop('Id',axis=1,inplace=True)

In [7]:
df_train.fillna(20,inplace=True)

In [8]:
y=df_train['SalePrice'].values
x=df_train.drop('SalePrice',axis=1)

In [9]:
x=x.values

In [10]:
df_train.shape

(1460, 80)

In [11]:
from numpy.linalg import inv

In [12]:
beta_coeff=np.dot((np.dot(x.T,inv(np.dot(x,x.T)))),y)

In [13]:
beta_coeff

array([-4.16791286e+03, -1.49965464e+05, -8.03311363e+03,  6.01252117e+03,
        1.04376197e+06,  2.37057612e+05,  1.01008708e+05, -1.44423183e+05,
        2.42080629e+06, -1.18900395e+04, -2.47959773e+05, -2.40605559e+04,
        1.67840123e+04, -3.67816572e+05, -2.12794634e+04,  2.89513467e+04,
       -7.36176820e+04,  7.93518550e+04, -8.10065885e+03,  1.04864347e+04,
       -1.24219273e+05, -1.49299810e+04,  9.40502378e+04, -9.73253546e+04,
        6.53566398e+04,  1.48299744e+03,  7.80170056e+04,  4.77143467e+04,
        6.64014404e+04, -1.19398958e+05,  3.55752631e+04,  1.67717940e+05,
        1.03266418e+05, -3.09245010e+01, -4.18740471e+04, -1.01282343e+02,
        6.93206022e+02,  1.25472204e+02,  3.11116133e+05,  3.72322896e+04,
        1.94731785e+05, -5.44106645e+04,  2.84950201e+02,  1.34220802e+03,
       -8.25469296e+02,  1.92052307e+03,  2.14726135e+05,  4.33059153e+05,
        3.91378827e+05,  9.14139852e+04,  9.47756617e+04,  1.36523550e+06,
        6.94714020e+04, -3.54833020e+05,  4.73340255e+03, -7.17035765e+04,
       -4.65764313e+04, -1.64962895e+04,  1.90112973e+03, -1.09305048e+05,
        1.50669196e+02,  8.16642747e+02, -1.88476616e+05,  2.25516734e+05,
        2.36219915e+05,  9.05662775e+02,  1.25694889e+02, -2.32241597e+02,
       -3.40062161e+03, -3.26442734e+03, -2.94689641e+03, -5.30378817e+05,
       -9.39509757e+04, -1.23682860e+05, -1.73064681e+01, -1.07124572e+04,
        5.35195587e+03,  2.02365295e+04, -4.77311743e+04])

In [14]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [15]:
pd.DataFrame([beta_coeff,x.columns]).T

AttributeError: 'numpy.ndarray' object has no attribute 'columns'